/**
 * Company mock data
 */
import type { CompanyMember, CompanyChannel, CompanyMessage } from '../types/constants';

// Re-export types for backwards compatibility
export { type CompanyMember, type CompanyChannel, type CompanyMessage } from '../types/constants';

export const MOCK_COMPANY_ID = 'org_b64test123';

export const MOCK_COMPANY_MEMBERS: CompanyMember[] = [
  {
    userId: 'usr_001',
    displayName: 'Анна Волкова',
    role: 'admin',
    publicKey: 'pub_001',
    joinedAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    lastActive: Date.now() - 5 * 60 * 1000,
    online: true,
    office: 'moscow',
  },
  {
    userId: 'usr_002',
    displayName: 'Дмитрий Козлов',
    role: 'member',
    publicKey: 'pub_002',
    joinedAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    lastActive: Date.now() - 30 * 60 * 1000,
    online: true,
    office: 'moscow',
  },
  {
    userId: 'usr_003',
    displayName: 'Елена Соколова',
    role: 'member',
    publicKey: 'pub_003',
    joinedAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    lastActive: Date.now() - 2 * 60 * 60 * 1000,
    online: false,
    office: 'moscow',
  },
  {
    userId: 'usr_004',
    displayName: 'Иван Петров',
    role: 'member',
    publicKey: 'pub_004',
    joinedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    lastActive: Date.now() - 15 * 60 * 1000,
    online: true,
    office: 'london',
  },
  {
    userId: 'usr_005',
    displayName: 'Мария Новикова',
    role: 'member',
    publicKey: 'pub_005',
    joinedAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    lastActive: Date.now() - 45 * 60 * 1000,
    online: false,
    office: 'london',
  },
  {
    userId: 'usr_006',
    displayName: 'Алексей Морозов',
    role: 'member',
    publicKey: 'pub_006',
    joinedAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
    lastActive: Date.now() - 3 * 60 * 60 * 1000,
    online: false,
    office: 'moscow',
  },
];

export const MOCK_COMPANY_CHANNELS: CompanyChannel[] = [
  {
    id: 'company-all',
    companyId: MOCK_COMPANY_ID,
    name: 'Весь офис',
    description: 'Общий канал для всех сотрудников',
    unread: 3,
    memberCount: 6,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'company-office-moscow',
    companyId: MOCK_COMPANY_ID,
    officeId: 'moscow',
    name: 'Офис Москва',
    description: 'Только для сотрудников в Москве',
    unread: 1,
    memberCount: 4,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'company-office-london',
    companyId: MOCK_COMPANY_ID,
    officeId: 'london',
    name: 'Офис Лондон',
    description: 'Только для сотрудников в Лондоне',
    unread: 0,
    memberCount: 2,
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'company-dev',
    companyId: MOCK_COMPANY_ID,
    name: 'Разработка',
    description: 'Технические обсуждения',
    unread: 12,
    memberCount: 4,
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'company-random',
    companyId: MOCK_COMPANY_ID,
    name: 'Случайное',
    description: 'Неслужебное общение',
    unread: 0,
    memberCount: 5,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
];

export const MOCK_COMPANY_MESSAGES: CompanyMessage[] = [
  {
    id: 'cm-001',
    channelId: 'company-all',
    senderId: 'usr_001',
    senderName: 'Анна Волкова',
    text: 'Доброе утро! Сегодня в 14:00 общий стендап. Не забывайте готовить статусы.',
    timestamp: Date.now() - 2 * 60 * 60 * 1000,
    status: 'read',
    reactions: { '👍': ['usr_002', 'usr_004'], '🙌': ['usr_003'] },
  },
  {
    id: 'cm-002',
    channelId: 'company-all',
    senderId: 'usr_002',
    senderName: 'Дмитрий Козлов',
    text: 'Анна, не могу подключиться — у меня интермиттент соединение. Могу подключиться по телефону?',
    timestamp: Date.now() - 2 * 60 * 60 * 1000 + 5 * 60 * 1000,
    status: 'delivered',
    replyTo: { id: 'cm-001', senderName: 'Анна Волкова', text: 'Доброе утро! Сегодня в 14:00 общий стендап...' },
  },
  {
    id: 'cm-003',
    channelId: 'company-all',
    senderId: 'usr_004',
    senderName: 'Иван Петров',
    text: 'В Лондоне тоже подключимся. Тема сегодня — запуск v2.4 в прод.',
    timestamp: Date.now() - 90 * 60 * 1000,
    status: 'read',
  },
  {
    id: 'cm-004',
    channelId: 'company-dev',
    senderId: 'usr_003',
    senderName: 'Елена Соколова',
    text: 'Коллеги, ревью PR #847 уже 3 дня висит. Может, кто-нибудь посмотрит?',
    timestamp: Date.now() - 4 * 60 * 60 * 1000,
    status: 'read',
    reactions: { '👀': ['usr_001', 'usr_006'] },
  },
  {
    id: 'cm-005',
    channelId: 'company-dev',
    senderId: 'usr_001',
    senderName: 'Анна Волкова',
    text: 'Смотрю сейчас. Там конфликт в AuthContext — быстро починю.',
    timestamp: Date.now() - 3 * 60 * 60 * 1000,
    status: 'read',
    replyTo: { id: 'cm-004', senderName: 'Елена Соколова', text: 'Коллеги, ревью PR #847 уже 3 дня висит...' },
  },
  {
    id: 'cm-006',
    channelId: 'company-office-moscow',
    senderId: 'usr_006',
    senderName: 'Алексей Морозов',
    text: 'Кто-нибудь знает, где в новом офисе розетки под ноут?',
    timestamp: Date.now() - 30 * 60 * 1000,
    status: 'delivered',
    reactions: { '😅': ['usr_002'] },
  },
  {
    id: 'cm-007',
    channelId: 'company-random',
    senderId: 'usr_005',
    senderName: 'Мария Новикова',
    text: 'Кто идёт на корпоратив в пятницу? 🎉',
    timestamp: Date.now() - 5 * 60 * 60 * 1000,
    status: 'read',
    reactions: { '🎉': ['usr_001', 'usr_002', 'usr_004'], '🙋': ['usr_003'] },
  },
  {
    id: 'cm-008',
    channelId: 'company-random',
    senderId: 'usr_002',
    senderName: 'Дмитрий Козлов',
    text: 'Обязательно! Говорят, будет квиз с призами.',
    timestamp: Date.now() - 4.5 * 60 * 60 * 1000,
    status: 'read',
    replyTo: { id: 'cm-007', senderName: 'Мария Новикова', text: 'Кто идёт на корпоратив в пятницу? 🎉' },
  },
];

export const MOCK_COMPANY_OFFICES = [
  { id: 'moscow', name: 'Москва', country: 'Россия', flag: '🇷🇺' },
  { id: 'london', name: 'Лондон', country: 'Великобритания', flag: '🇬🇧' },
];
