export const STORAGE_KEYS = {
  THEME: 'app_theme',
  LANGUAGE: 'app_language',
  LOCK_ATTEMPTS: 'app_lock_attempts',
  LOCK_BLOCKED_UNTIL: 'app_lock_blocked_until',
  LOCK_PIN_HASH: 'app_lock_pin_hash',
  LOCK_SALT: 'app_lock_salt',
  DRAFTS: 'mess_drafts',
  SAVED_MESSAGES: 'mess_saved_messages',
  DND_ENABLED: 'app_dnd_enabled',
  DND_FROM: 'app_dnd_from',
  DND_TO: 'app_dnd_to',
  PRIORITY_CONTACTS: 'app_priority_contacts',
  EQ_PRESETS: 'eq_presets',
  ANONYMITY_CONFIG: 'anonymity_config',
  MUSIC_PLAYER: 'music_player_data',
  STORAGE_IMPORT: 'mess_storage_import',
  BLOCKED_BACKENDS: 'mess_blocked_backends',
  PROXY: 'app_proxy',
  PROXY_URL: 'app_proxy_url',
  TOR_BRIDGE: 'app_tor_bridge',
  OBFUSCATION: 'app_obfuscation',
  RECOVERY_HASH: 'app_recovery_hash',
  SIGNALLING_POOL: 'mess_signalling_pool',
  RATE_LIMITS: '__mess_rate_limits',
  SECURITY_LOG: '__mess_security_log',
  NEXUS_STORAGE: 'nexus-messenger-storage',
} as const

export type StorageKey = (typeof STORAGE_KEYS)[keyof typeof STORAGE_KEYS]
