/**
 * Company group-key cryptography.
 *
 * A single symmetric AES-256-GCM group key protects team data (CRM sync
 * envelopes, future E2E chat transport). The key is generated by the admin
 * on company creation and wrapped per-member via X25519 ECDH (ECIES-style),
 * so each member can independently recover it. No plaintext group key ever
 * leaves the device; only wrapped (encrypted) blobs are exchanged.
 *
 * All crypto is Web Crypto (SubtleCrypto). No network, no telemetry.
 */

import { generateX25519KeyPair, x25519DH, b64encode, b64decode } from '../../lib/crypto/cryptoCore';
import type { CompanyEnvelope, WrappedKey } from './types';

function randomBytes(n: number): Uint8Array {
  const a = new Uint8Array(n);
  crypto.getRandomValues(a);
  return a;
}

const enc = new TextEncoder();
const dec = new TextDecoder();

/** Generate a fresh extractable AES-256-GCM group key. */
export async function generateGroupKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, true, ['encrypt', 'decrypt']);
}

/** Export a group key to a base64 raw string for local persistence. */
export async function exportRawKey(key: CryptoKey): Promise<string> {
  const raw = await crypto.subtle.exportKey('raw', key);
  return b64encode(new Uint8Array(raw));
}

/** Re-import a base64 raw string into a group key. */
export async function importRawKey(b64: string): Promise<CryptoKey> {
  const raw = b64decode(b64);
  return crypto.subtle.importKey('raw', raw, 'AES-GCM', true, ['encrypt', 'decrypt']);
}

/**
 * Wrap a group key for a single member using an ephemeral X25519 keypair.
 * Only that member's X25519 secret can unwrap it.
 */
export async function wrapGroupKeyForMember(
  groupKey: CryptoKey,
  memberX25519PubB64: string,
): Promise<WrappedKey> {
  const ephemeral = generateX25519KeyPair();
  const memberPub = b64decode(memberX25519PubB64);
  const shared = x25519DH(ephemeral.secretKey, memberPub);
  const aesKey = await crypto.subtle.importKey('raw', shared.slice(0, 32), 'AES-GCM', false, ['encrypt']);
  const rawGroup = await crypto.subtle.exportKey('raw', groupKey);
  const iv = randomBytes(12);
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, aesKey, new Uint8Array(rawGroup));
  return {
    memberPublicKey: memberX25519PubB64,
    ephemeralPublicKey: b64encode(ephemeral.publicKey),
    ciphertext: b64encode(new Uint8Array(ct)),
    nonce: b64encode(iv),
  };
}

/** Recover a group key from a wrapped blob using the member's X25519 secret. */
export async function unwrapGroupKey(wrapped: WrappedKey, myX25519Secret: Uint8Array): Promise<CryptoKey> {
  const ephemeralPub = b64decode(wrapped.ephemeralPublicKey);
  const shared = x25519DH(myX25519Secret, ephemeralPub);
  const aesKey = await crypto.subtle.importKey('raw', shared.slice(0, 32), 'AES-GCM', false, ['decrypt']);
  const iv = b64decode(wrapped.nonce);
  const ct = b64decode(wrapped.ciphertext);
  const rawGroup = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, aesKey, ct);
  return importRawKey(b64encode(new Uint8Array(rawGroup)));
}

/** Encrypt an arbitrary string into a signed-for-team CompanyEnvelope. */
export async function sealEnvelope(
  groupKey: CryptoKey,
  meta: { companyId: string; senderPubKey: string; groupKeyVersion: number; text: string },
): Promise<CompanyEnvelope> {
  const iv = randomBytes(12);
  const ct = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, groupKey, enc.encode(meta.text));
  return {
    iv: b64encode(iv),
    ciphertext: b64encode(new Uint8Array(ct)),
    senderPubKey: meta.senderPubKey,
    companyId: meta.companyId,
    groupKeyVersion: meta.groupKeyVersion,
    timestamp: Date.now(),
  };
}

/** Decrypt a CompanyEnvelope back into its plaintext string. */
export async function openEnvelope(groupKey: CryptoKey, env: CompanyEnvelope): Promise<string> {
  const iv = b64decode(env.iv);
  const ct = b64decode(env.ciphertext);
  const plain = await crypto.subtle.decrypt({ name: 'AES-GCM', iv }, groupKey, ct);
  return dec.decode(plain);
}
