/**
 * Settings defaults for useLocalStorage hooks
 */
export const DEFAULTS = {
  language: 'ru',
  notifications: true,
  twoFactor: false,
  proxy: false,
  spamFilter: true,
  pwaBanner: true,
  deadMansSwitch: '6 months',
  mediaAutoLoad: 'Wi-Fi',
  selfDestructDefault: 'Off',
  obfuscationMode: 'xorshroud',
  obfuscationEnabled: true,
  proxyUrl: '',
  torBridge: 'None',
  relayBackend: 'direct',
  autoReconnect: true,
  p2pMesh: true,
  visNumber: 'Nobody',
  visActivity: 'My contacts',
  uiAnimations: true,
  fontSize: 'Medium',
  dndEnabled: false,
  dndFrom: '22:00',
  dndTo: '08:00',
  priorityContacts: 'Joker,Design Team',
};

/** Default key names used by localStorage */
export const KEYS = {
  LANGUAGE: 'app_language',
  NOTIFICATIONS: 'app_notifications',
  TWO_FACTOR: 'app_2fa',
  PROXY: 'app_proxy',
  SPAM_FILTER: 'app_spam_filter',
  PWA_BANNER: 'app_pwa_banner',
  DEAD_MANS_SWITCH: 'app_dead_mans_switch',
  MEDIA_AUTO_LOAD: 'app_media_autoload',
  SELF_DESTRUCT: 'app_self_destruct',
  OBFUSCATION_MODE: 'app_obfuscation',
  OBFUSCATION_ENABLED: 'app_obfuscation_enabled',
  PROXY_URL: 'app_proxy_url',
  TOR_BRIDGE: 'app_tor_bridge',
  RELAY_BACKEND: 'app_relay_backend',
  AUTO_RECONNECT: 'app_auto_reconnect',
  P2P_MESH: 'app_p2p_mesh',
  VIS_NUMBER: 'app_vis_number',
  VIS_ACTIVITY: 'app_vis_activity',
  UI_ANIMATIONS: 'app_ui_animations',
  FONT_SIZE: 'app_font_size',
  DND_ENABLED: 'app_dnd_enabled',
  DND_FROM: 'app_dnd_from',
  DND_TO: 'app_dnd_to',
  PRIORITY_CONTACTS: 'app_priority_contacts',
};
